### ISSUE TITLE
Adding to existing save

### ISSUE THREAD

**Issue by robot256** [garrotte13/TurretPod#1]
When I installed the Turret Pods and Vehicle Grids (at the same time) and loaded an existing game (that previously had neither), existing vehicles would not load their turret pods until I mined and replaced the vehicle.

You can solve this by running code in on_configuration_changed to search all surfaces for existing vehicles, check if they have the proper grids, and register them if they are not already registered.  The LuaSurface::find_entities_filtered is great for this.  on_configuration_changed will run every time a mod is installed, uninstalled, or a startup setting is changed.  That way you can update existing vehicles if they gain or lose a grid.

**Comment by garrotte13** [comment]
thanks for notice.
